tissue_correspondance = [
    ['Breast', 'TCGA-BRCA'],
    ['Skin', 'TCGA-SKCM'],
    ['Large Intestine', 'Small Intestine', 'TCGA-COAD', 'TCGA-READ'],
    ['Lung', 'TCGA-MESO', 'TCGA-LUAD', 'TCGA-LUSC'],
    ['Head and Neck', 'TCGA-HNSC'],
    ['Prostate', 'TCGA-PRAD'],
    ['Pancreas', 'TCGA-PAAD'],
    ['Brain', 'Central Nervous System', 'TCGA-GBM', 'TCGA-LGG'],
    ['Blood', 'Haematopoietic and Lymphoid', 'TARGET-AML', 'TARGET-ALL-P2', 'TCGA-DLBC', 'TCGA-LAML'],
    ['Kidney', 'TCGA-KICH', 'TCGA-KIRC', 'TCGA-KIRP'],
    ['Ovary', 'TCGA-OV'],
    ['Uterus', 'TCGA-UCS', 'TCGA-UCEC'],
    ['Liver', 'TCGA-CHOL', 'TCGA-LIHC'],
    ['Thyroid', 'TCGA-THCA'],
    ['Stomach', 'TCGA-STAD'],
    ['Bladder', 'TCGA-BLCA'],
    ['Cervix', 'Vulva', 'TCGA-CESC'],
    ['Esophagus', 'TCGA-ESCA'],
    ['Peripheral Nervous System', 'Adrenal Gland', 'TCGA-PCPG', 'TCGA-ACC'],
    ['Bone', 'Soft Tissue', 'TCGA-SARC'],
    ['Testis', 'TCGA-TGCT'],
    ['Thymus', 'TCGA-THYM'],
    ['Eye', 'TCGA-UVM'],
    ['Endometrium']
]

colors = ['green',
          'red', 
          'darksalmon',
            'orchid',
          'gold', 
          'olivedrab', 
          'deepskyblue', 
          'navy',
          'm', 
          'sandybrown',
          'slategray',
          'chocolate',
          'silver',
          'coral', 
          'magenta',
          'orange',
          'violet', 
          'yellowgreen', 
          'pink', 
          'orchid',
          'darkblue',
          'plum',
          'khaki',
          'sienna',
          'tomato']
assert len(colors) >= len(tissue_correspondance)